### ISSUE TITLE
OSMesa Dataset for OSM records

### ISSUE THREAD

**Issue by echeipesh** [azavea/osmesa#105]
Currently OSMesa has streaming data sources that read augmented diffs and changsets:

```
osmesa.common.streaming.AugmentedDiffProvider
osmesa.common.streaming.ChangeProvider
osmesa.common.streaming.ChangesetProvider
```

The logic backing these can be used to implement OSMesa DataSource that will consume the same files given `start` and `end` date and produce a `Dataset[OSM]` `DStream[OSM]`

This is very useful for debugging, working in Zeppelin notebooks and creating backfill batch jobs.

Enables: https://github.com/azavea/osmesa/issues/48

**Comment by mojodna** [comment]
See #106 for a PR covering this.
