### ISSUE TITLE
Generate statistics with Zeppelin and VectorPipe directly from ORC

### ISSUE THREAD

**Issue by lossyrob** [azavea/osmesa#11]
## Per Changeset stats
- [ ] km of roads edited
- [ ] number of road edits
- [ ] number of buildings edited
- [ ] number of POIs edited (amenity)
- [ ] number of waterway edits
- [ ] km of waterways edited
- [ ] extent of edits
- [ ] countries edited in
- [ ] hashtags participated in

## Per Hashtag stats
- [ ] number of participants
- [ ] km of roads edited
- [ ] number of buildings edited
- [ ] number of POIs edited (amenity)
- [ ] km of waterways edited

**Comment by fosskers** [comment]
The GT team has been having a lot of issues with Zeppelin lately. Is there value in prototyping locally first?

Also, do we have a decent history file to work off of?

**Comment by moradology** [comment]
Getting a small EMR cluster up and playing around on Zeppelin (which I can assist with if you encounter trouble) seems to me the simplest approach. I'll assist with getting the Zeppelin instance running if that proves difficult

**Comment by fosskers** [comment]
We can't do buildings yet, as we haven't ported over the `Line <-> Polygon` reassociation code for Planet History. Should I do that first?

**Comment by kamicut** [comment]
A couple more stats would be useful to do a breakdown chart (Type of edits pie chart)

- Number of roads edited
- Number of waterways edited

**Comment by fosskers** [comment]
Those should be easy to get in passing while doing the more involved ones.

**Comment by mojodna** [comment]
These statistics are all calculated now.
