### ISSUE TITLE
Fix try-with-resources blocks in replication sources

### ISSUE THREAD

**Issue by mojodna** [azavea/osmesa#120]
Change/changeset replication (`ChangeSource`, `ChangesetSource`) include try-with-resources blocks to handle fetching and decompression. They appear to be incorrect; see https://medium.com/@dkomanov/scala-try-with-resources-735baad0fd7d for notes.

_Originally posted by @mojodna in https://github.com/azavea/osmesa/pull/106_

**Comment by jpolchlo** [comment]
Does this still apply after killing `osmesa.common`?  Should this issue be transferred over to the geotrellis/vectorpipe repository?

**Comment by mojodna** [comment]
Possibly? It's also possible that Spark's retry behavior makes this issue moot since it doesn't need to fully clean up after itself.
