### ISSUE TITLE
Thinking in changesets

### ISSUE THREAD

**Issue by kamicut** [azavea/osmesa#15]
I had a conversation with @fosskers about the `/users/uid` route and we were talking about the underlying mechanism for generating the statistics. The original thinking was that there would be underlying `users` and `campaigns` tables in HBase that aggregated statistics such as "road count by user", "building count by user" at ingest time.

I want to make the case that the underlying table should be `changesets` and that `users` and `hashtags` are materialized views of grouping queries. (This was first brought up by @mojodna)
1. Changesets are the primitive datatype above osm entities (node, way, relationships). A changesets has-a user and has-a hashtag.
2. By aggregating without keeping changeset timestamp information we lose some valuable granular information. For example, we wouldn't know "when" a user has passed a certain threshold to award them a badge.

While I don't think osmesa should handle or be aware of user-end terms like "badges", it should allow downstream apps to process that granular information. By flipping the model of the Query API to "grab changesets filtered by user/campaign", we can create these use cases downstream.

**Comment by lossyrob** [comment]
My only concern in going from only users/hashtags to only changesets is, there's a lot more changeset data to be served rather then a pre-rolled up user/changeset stats row pre-baked and always-updated. This has impacts on the query server performance, and for what the clients of the API would need.

I think user/hashtags AND changesets is a fine idea. Adding a changeset endpoint to the API could work. In the short-term, concentrating on getting the user and hashtag endpoints completed seems like a good thing to do. i.e. I would make the case for not flipping right now, but adding that endpoint after the user/hashtag endpoints are up.

**Comment by fosskers** [comment]
The pre-aggregated tables would certainly have a use, especially when displaying the leaderboards. We'd want the data to appear for user user pretty quickly.

**Comment by kamicut** [comment]
@lossyrob I understand the concern for query performance. The thing we would lose right now is (2) above, but this is something that we can tackle later on as you've suggested.

**Comment by mojodna** [comment]
This is more or less how stats aggregation works now.
