### ISSUE TITLE
Total edits appears not to update correctly for streaming updates

### ISSUE THREAD

**Issue by jpolchlo** [azavea/osmesa#165]
It has become apparent that the `total_edits` field of the `changesets` table is not updating in streaming jobs.  Need to investigate why this is occurring and create a fix.

Closes azavea/osmesa-stat-server#25

**Comment by echeipesh** [comment]
rebuilding the augdiff stream resolved the issue but the root cause is still unclear.

**Comment by CloudNiner** [comment]
Reopening this to better resolve after a discussion with @jpolchlo. There are significant discrepancies that weren't fixed by rebuilding the aug diff stream. I'm going to investigate a bit more and create a better fix for the counts, since they're significantly different on staging and production.

**Comment by CloudNiner** [comment]
Closed by #184
