### ISSUE TITLE
Generate development environment stack

### ISSUE THREAD

**Issue by lossyrob** [azavea/osmesa#2]
This will culminate in a `docker-compose.yml` and supporting scripts to be able to bring up the following components:

- [ ] HDFS
- [ ] ZooKeeper
- [ ] HBase with GeoMesa extensions
- [ ] GeoServer
- [ ] Zeppelin

Testing this setup should include some version of an ingest and view through GeoServer that matches http://www.geomesa.org/documentation/tutorials/geomesa-quickstart-hbase.html, as well as accessing GeoMesa through SparkSQL in a Zeppelin notebook.

References:
https://github.com/geodocker/geodocker-geomesa
https://github.com/ccri/cloud-local
https://github.com/geotrellis/geodocker-cluster/tree/daunnc/hbase/hbase

**Comment by lossyrob** [comment]
@azavea/operations relevant to #1 and might be useful to track.

**Comment by hectcastro** [comment]
Wanted to add a comment here to consider targeting a central EMR cluster with all of these dependencies vs. trying to sort out how to manage them locally in a way that simulates the target environment (maybe with GeoServer as the exception).
