### ISSUE TITLE
Performance testing query server

### ISSUE THREAD

**Issue by moradology** [azavea/osmesa#7]
When comparing GM/GW performance roughly one year ago, the GeoTrellis team produced some tooling for testing the performance of queries against accumulo and hbase stores. We should reuse some of that effort here to get a sense of query performance in the relatively exotic `hbase` on top of `s3` architecture we're pursuing

**Comment by hectcastro** [comment]
A heads up that there is a decent looking tuning guide for performance [here](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-hbase-s3.html) under the **Properties for HBase on Amazon S3 Performance Tuning** section.

**Comment by mojodna** [comment]
Not relevant to the current approach in use.
